services:
  # Copy file from host then install pnpm packages for frontend and backend together
  initializer:
    image: node:23
    container_name: kingoh-initializer
    restart: on-failure
    volumes:
      - ./:/src/
      - kingoh:/app/
    command: /bin/bash -c "
      cp /src/* /app/ -r &&

      npm install -g pnpm@latest &&
      echo '===== app/backend =====' &&
      cd /app/backend/ && pnpm install --force &&
      echo '===== app/frontend =====' &&
      cd /app/frontend/ && pnpm install --force
      "

  # Sync files from host to docker volume every 5 seconds so hot reloads work
  syncer:
    image: servercontainers/rsync
    container_name: kingoh-syncer
    volumes:
      - ./:/src/
      - kingoh:/app/
    command: /bin/bash -c "
      while true; do
      rsync -avch --exclude=node_modules/ --exclude=.next/ --exclude=.pnpm-store/ --cvs-exclude /src/ /app/ &&
      sleep 5;
      done;
      "
    depends_on:
      initializer:
        condition: service_completed_successfully

  backend:
    image: node:23
    container_name: kingoh-backend
    restart: on-failure
    env_file:
      - ./backend/.env
    working_dir: /app/backend/
    volumes:
      - kingoh:/app/
    command: /bin/bash -c "npm install -g pnpm@latest && pnpm run start:dev"
    depends_on:
      initializer:
        condition: service_completed_successfully
    ports:
      - 3001:3000
    networks:
      server:

  frontend:
    image: node:23
    container_name: kingoh-frontend
    restart: on-failure
    working_dir: /app/frontend/
    volumes:
      - kingoh:/app/
    command: /bin/bash -c "npm install -g pnpm@latest && pnpm run dev"
    depends_on:
      initializer:
        condition: service_completed_successfully
    ports:
      - 3000:3000
    networks:
      server:

volumes:
  kingoh:

networks:
  internet:
  server:
